server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://rm-2zecekp430kv77k755o.mysql.rds.aliyuncs.com:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: fangyang
    password: 224206799qqFy

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

